### ISSUE TITLE
Licensing questions

### ISSUE THREAD

**Issue by spotaws** [NVIDIAGameWorks/NvCloth#60]
I have some questions about the licensing on this code.

1. The "Nvidia Source Code License (1-Way Commercial)" seems to be a modification of the Amazon Software License, but with the use restrictions (and some of the patent language) removed. As this license is not an Open Source Initiative (OSI) approved Open Source license, would it be possible to replace it with a proper open source license? I think Apache 2.0 would be a similar license.
2. If not, you should at least clean up the references in that license to the sections that were removed. Specifically, there are two references to a non-existent "Section 2.2".
3. The header files (include/NvCloth) and source code (src/) all contain a different license from the Nvidia Source Code License (1-Way Commercial). Even if you interpret the beginning "This code contains NVIDIA Confidential Information and is disclosed to you under a form of NVIDIA software license agreement provided separately to you." as a reference to the other license, there is an additional restriction in the embedded license which make it clearly non-open source. Specifically:

`// NVIDIA Corporation products are not authorized for use as critical
// components in life support devices or systems without express written approval of
// NVIDIA Corporation.`

Would it be possible to remove that language? The ideal change would be to remove all of the confusing licensing in each of the source files and either point to the master license by reference or by including a copy of it there. If that is not possible, simply removing the use restriction might suffice.

**Comment by amoravanszky** [comment]
Thank you for finding these issues.  We will be pushing an update soon that should address the clearly broken reference to section 2.2.

The license is, however, deliberately different from e.g. BSD3 Open Source.  This is not an accident and will be maintained this way.  

In particular, I would personally not trust my life on this code working perfectly, however, and neither should anyone else, so we will not be removing any restrictions around use in life support devices.  As you can see, even our license agreements can have bugs!

**Comment by mtamis-NV** [comment]
The Section 2.2 references are now fixed on latest master.

**Comment by spotaws** [comment]
Thanks for fixing the internal issues with the base license.

While the choice of licensing belongs entirely to you, allow me to point out that your custom licensing would probably be considered open source, if not for the use restriction clause.

I do not think its is likely that this code would find its way into a "life support device or system", however, PCs are often multipurpose, and what is a "critical component" is up for debate. I would argue that what NVIDIA really wants here is limitation of liability, which is already present in Section 5 of the license.

This situation is analogous to a license that Sun used for a while on some of its Java components, which was open source, except for the inclusion of this line:

`You acknowledge that this software is not designed, licensed or intended for use in the design, construction, operation or maintenance of any nuclear facility.`

Through correspondence with Sun (and later Oracle), they agreed that the probability of Java code being used to design, construct, operate, or maintain a nuclear facility was low (but not impossible), and that their real concern was liability. Additionally, the presence of this restriction was preventing code under that license from being open source, and being included in Linux distributions (or other open source projects). They agreed to reword that line to make it clear that it was not a use restriction, and it changed to this:

`You acknowledge that this software is not designed or intended for use in the design, construction, operation or maintenance of any nuclear facility.`

Might it be possible for NVIDIA to take a similar approach? The equivalent rewording could look something like this:

`NVIDIA Corporation products are not designed or intended for use as critical components in life support devices or systems.`

This phrasing does not restrict usage, but makes it clear from a legal liability perspective that NVIDIA did not design or intend for the software to be used in that specific manner.

I am asking because this code is very useful (and in fact, a dependency for other open source code) and it is disappointing to see it so close to open source. Thanks in advance.
